### ISSUE TITLE
js files get placed in src/, not in lib/js/src

### ISSUE THREAD

**Issue by SuperFluffy** [bsansouci/reprocessing-example#15]
I have managed to get the examples running using both the `native` and the `js` backends. I am surprised, however, that `bsb -make-world -native js` places the resulting `index.js` not in `lib/js/src/`, as is expected by the `index.html` file, but puts it in `src/`.

In fact, I don't have `lib/js/src`, only a `lib/bs/js/src`, with the following contents:

```bash
% ls -1 lib/bs/js/src/
index.cmi
index.cmj
index.cmt
index.mlast
index.mlast.d
IndexHot.cmi
IndexHot.cmj
IndexHot.cmt
IndexHot.mlast
IndexHot.mlast.d
```

Why the discrepancy?

**Comment by bsansouci** [comment]
There’s an option in bsconfig to in-line the generated is called “in-source”, see https://bucklescript.github.io/docs/en/build-configuration#package-specs

**Comment by SuperFluffy** [comment]
Thanks for the reply! Yes, indeed, that was it. It's a `bsb -init .` default, and I guessed that the behaviour should be the same between your more bare `bsconfig.json` and the generated one.
