### ISSUE TITLE
Add github template functionnality to this repo

### ISSUE THREAD

**Issue by hnspn** [bsansouci/reprocessing-example#21]
There is new repository template functionality offered by [Github](https://help.github.com/en/articles/creating-a-template-repository) that allow users to click a button to generate a repo based on the template.

I think this is good because a link to the original template is added to generated repos and this allow forks to be used for real project forking to add new functionality or make contributions.
Also adds a `/generate` endpoint if you want to programmatically generate a repo in a tutorial.

Here are [steps](https://help.github.com/en/articles/creating-a-repository-from-a-template) to make this repository a template.

I can't think of a reason not to add this.

**Comment by bsansouci** [comment]
Great idea, thanks! Tell me if it works :)

**Comment by hnspn** [comment]
works perfectly
thanks
