### ISSUE TITLE
Example fails because of library naming issues

### ISSUE THREAD

**Issue by StrykerKKD** [bsansouci/reprocessing-example#4]
I got these two errors by simply following the instructions in the readme.

First error:
`127.0.0.1 - - [14/Feb/2018 22:39:37] code 404, message File not found
127.0.0.1 - - [14/Feb/2018 22:39:37] "GET /node_modules/Reprocessing/lib/js/src/Reprocessing.js HTTP/1.1" 404 -`
Cause: In node_modules the Reprocessing library was with a lowercase first letter: "reprocessing".
Fix: Rename reprocessing to Reprocessing in node_modules.

Second error:
`127.0.0.1 - - [14/Feb/2018 22:46:14] code 404, message File not found
127.0.0.1 - - [14/Feb/2018 22:46:14] "GET /node_modules/reasongl/lib/js/src/RGLConstants.js HTTP/1.1" 404 -`
Cause: In node_modules the reasongl library started with uppercase first letter: Reasongl.
Fix: Rename Reasongl to reasongl in node_modules.

**Comment by Schmavery** [comment]
:( thanks for letting us know. We'll try to sort this out. Unfortunately me and @bsansouci both dev mainly on osx which makes these problems less obvious, but we're try to iron out the experience on linux as well.
